deepspeed dynamicat/training/training_pipeline.py \
  --global_batch_size 32 \
  --batch_size_per_gpu 4 \
  --planned_tensor_file_path test/test_jsonl_data_GPUMemoryRestricted_15000.pt \
  --dataset_specific_task_type sft \
  --model_path test/test_model \
  --zero_stage 2 \
  --use_bf16 \
  --learning_rate 1e-5 \
  --use_tensorboard \
  --num_epochs 3 \
  --checkpoint_save_path test/test_model_save_ds_train